"""categ_global

Revision ID: 091b7f2999a6
Revises: b34f38f89f72
Create Date: 2025-12-01 19:43:42.865530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091b7f2999a6'
down_revision: Union[str, Sequence[str], None] = 'b34f38f89f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
