"""Agregar tabla detalle ingreso

Revision ID: 3155a1478e4f
Revises: 037eb81bd7cb
Create Date: 2025-12-04 21:05:51.606732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3155a1478e4f'
down_revision: Union[str, Sequence[str], None] = '037eb81bd7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingreso_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingreso_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ingresos', sa.Column('monto_total', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False))
    op.drop_constraint(op.f('ingresos_category_id_fkey'), 'ingresos', type_='foreignkey')
    op.drop_column('ingresos', 'category_id')
    op.drop_column('ingresos', 'monto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingresos', sa.Column('monto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('ingresos', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ingresos_category_id_fkey'), 'ingresos', 'categories', ['category_id'], ['id'])
    op.drop_column('ingresos', 'monto_total')
    op.drop_table('ingreso_items')
    # ### end Alembic commands ###
