"""modif ingreso

Revision ID: 5c316c789cf4
Revises: 3155a1478e4f
Create Date: 2025-12-04 22:12:25.494080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c316c789cf4'
down_revision: Union[str, Sequence[str], None] = '3155a1478e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingresos', 'fuente',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingresos', 'fuente',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
