"""fix category uniqueness indices

Revision ID: e6bfb740b6c0
Revises: 56eccd1c30b6
Create Date: 2025-12-05 23:53:23.764755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bfb740b6c0'
down_revision: Union[str, Sequence[str], None] = '56eccd1c30b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_constraint(op.f('uq_category_name_user'), 'categories', type_='unique')
    op.create_index('ix_categories_name_global', 'categories', ['name'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('ix_categories_name_user_id', 'categories', ['name', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name_user_id', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_categories_name_global', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.create_unique_constraint(op.f('uq_category_name_user'), 'categories', ['name', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    # ### end Alembic commands ###
