"""fix expenses

Revision ID: e7343b38bb0c
Revises: e6bfb740b6c0
Create Date: 2025-12-08 00:33:38.061066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7343b38bb0c'
down_revision: Union[str, Sequence[str], None] = 'e6bfb740b6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name_global'), table_name='categories', postgresql_where='(user_id IS NULL)')
    op.drop_index(op.f('ix_categories_name_user_id'), table_name='categories', postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index('ix_categories_name_global_unique', 'categories', ['name'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('ix_categories_name_user_unique', 'categories', ['name', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.alter_column('expense_items', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('expense_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_expense_items_category_id'), 'expense_items', ['category_id'], unique=False)
    op.create_index('ix_expense_items_expense_id', 'expense_items', ['expense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expense_items_expense_id', table_name='expense_items')
    op.drop_index(op.f('ix_expense_items_category_id'), table_name='expense_items')
    op.alter_column('expense_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expense_items', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.drop_index('ix_categories_name_user_unique', table_name='categories', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_categories_name_global_unique', table_name='categories', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.create_index(op.f('ix_categories_name_user_id'), 'categories', ['name', 'user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('ix_categories_name_global'), 'categories', ['name'], unique=True, postgresql_where='(user_id IS NULL)')
    # ### end Alembic commands ###
