"""Añadir campo telegram a la bd. Usuarios

Revision ID: f09656c51856
Revises: 091b7f2999a6
Create Date: 2025-12-02 06:24:16.275012

"""
from typing import Sequence, Union

from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09656c51856'
down_revision: Union[str, Sequence[str], None] = '091b7f2999a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True, comment='Telegram chat ID for bot integration'))
    
    op.add_column(
        'users',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("NOW()")
        )
    )
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###
